# Generated by Django 2.2.6 on 2020-02-28 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies_list', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergic_food',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_accounts',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, default=0, help_text='Please use centimeters', null=True)),
                ('weight', models.FloatField(blank=True, default=0, help_text='Please use lbs', null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('target_calorie_intake', models.FloatField(blank=True, default=0, null=True)),
                ('preferred_meal', models.CharField(blank=True, default='', max_length=30)),
                ('allergic_food', models.CharField(blank=True, default='', max_length=30)),
                ('work_out_level', models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='', help_text='With 5 being the highest', max_length=1)),
                ('dietary_preferences', models.CharField(blank=True, default='', max_length=30)),
                ('health_history', models.CharField(blank=True, default='', max_length=30)),
                ('preferred_breakfast_time', models.CharField(blank=True, default='', max_length=30)),
                ('preferred_lunch_time', models.CharField(blank=True, default='', max_length=30)),
                ('preferred_dinner_time', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
