# Generated by Django 2.2.6 on 2020-03-23 17:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200303_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=256)),
                ('recipe_name', models.CharField(max_length=256)),
                ('marketing_description', models.CharField(max_length=256)),
                ('allergen_attributes', models.CharField(max_length=256)),
                ('dietary_attributes', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'serviceRecipeNutrition',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Sedentary'), (2, 'Lightly Active'), (3, 'Moderately Active'), (4, 'Active')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, '15-20'), (2, '20-25'), (3, '25-30'), (4, '30-35'), (5, '35-40'), (6, '40-45'), (7, '45-50')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allergic_food',
            field=djongo.models.fields.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(blank=True, choices=[(1, '4\'0" - 4\'11"'), (2, '5\'0" - 5\'11"'), (3, '6\'0" - 6\'11"'), (4, '7\'0" - 7\'11"')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(1, 'Below 150lb'), (2, '150lb to 200lb'), (3, 'Over 200lb')], null=True),
        ),
    ]
