# Generated by Django 2.2.6 on 2020-04-14 05:02

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200323_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.IntegerField()),
                ('egg', models.IntegerField()),
                ('peanut', models.IntegerField()),
                ('tree_nut', models.IntegerField()),
                ('soy', models.IntegerField()),
                ('wheat', models.IntegerField()),
                ('fish', models.IntegerField()),
                ('shellfish', models.IntegerField()),
                ('msg_monosodium_glutamate', models.IntegerField()),
                ('high_fructose_corn_syrup_hfcs', models.IntegerField()),
                ('mustard', models.IntegerField()),
                ('celery', models.IntegerField()),
                ('sesame', models.IntegerField()),
                ('gluten', models.IntegerField()),
                ('red_yellow_blue_dye', models.IntegerField()),
                ('gluten_free_per_fda', models.IntegerField()),
                ('non_gmo_claim', models.IntegerField()),
            ],
            options={
                'db_table': 'foodallergies',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FoodAllergies',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Sedentary'), (2, 'Moderately Active'), (3, 'Active')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allergic_food',
            field=djongo.models.fields.ListField(default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
