"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 2.2.6.

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/

Quick-start development settings - unsuitable for production
See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
   
A1. Modify debug status
A2. Modify allowed hosts
A3. Modify installed applications
A4. Modify database to be used
A5. Added DjangoRestFramework, modify pagination of API
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!k&z#(tg($8jl066i#^lsx4-ww4d_qn2=d0yqymqu#*ot0@32e'

# SECURITY WARNING: don't run with debug turned on in production!
# A1 Debug Status
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1:8000', '8000', 'localhost:8000', '52.234.228.184']
# ALLOWED_HOSTS = [os.environ['WEBSITE_SITE_NAME'] + '.azurewebsites.net', '127.0.0.1'] if 'WEBSITE_SITE_NAME' in os.environ else []
# A2 Allowed Hosts
ALLOWED_HOSTS=['*']

# A3 Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_readonly_field',
#Added apps
    'users.apps.UsersConfig',
    'rest_framework',
    'rest_framework.authtoken',
    # 'crispy_forms'
]

# AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# A4 Database Configuration
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#Mongo Atlas Database for testing
#username: mabryaf@gmail.com, password: Test1234
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'testingg1',
#         'HOST':"mongodb://mabry:fonseca@cluster0-shard-00-00-507kr.mongodb.net:27017,cluster0-shard-00-01-507kr.mongodb.net:27017,cluster0-shard-00-02-507kr.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority",
#     }
# }

#Azure Database for deployment
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'users',
        'ENFORCE_SCHEMA': False,
        'HOST':"127.0.0.1",
        # 'PORT':
        'USER': 'markoeats',
        'PASSWORD': 'Mark0eats@123',
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#A5 Set authentication and pagination
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    # ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

# CMS_MODERATOR = True
